# Uncomment the next line to define a global platform for your project
platform :ios, ‘8.0’

use_frameworks!

target 'SimpleProject' do

pod 'Masonry'
pod 'SVProgressHUD'
pod 'YYModel'
pod 'YYWebImage'
pod 'IQKeyboardManager'
pod 'ZFPlayer'

end
